version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka-network

  kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      networks:
        - kafka-network
  db:
    container_name: messenger
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: messenger

networks:
   kafka-network:
     driver: bridge